Repository varchar-io/nebula, pull requests merged in 2020-12, with the labels that each got.

#50 A bunch of updates to the core runtime
  CMakeLists.txt
  build.sh
  dev.md
  src/api/dsl/Dsl.cpp
  src/api/dsl/Dsl.h
  src/api/dsl/Query.h
  src/api/test/TestApi.cpp
  src/api/test/TestExpressions.cpp
  src/api/test/TestQuery.cpp
  src/api/udf/Between.h
  src/common/Common.cmake
  src/common/Memory.cpp
  src/common/Memory.h
  src/common/test/TestCommon.cpp
  src/common/test/TestSlice.cpp
  src/configs/bench.yml
  src/configs/test.yml
  src/execution/BlockManager.cpp
  src/execution/BlockManager.h
  src/execution/ExecutionPlan.cpp
  src/execution/ExecutionPlan.h
  src/execution/TableState.cpp
  src/execution/TableState.h
  src/execution/core/NodeClient.cpp
  src/execution/core/NodeClient.h
  src/execution/core/NodeExecutor.cpp
  src/execution/core/NodeExecutor.h
  src/execution/core/ServerExecutor.cpp
  src/execution/core/ServerExecutor.h
  src/execution/test/TestExec.cpp
  src/ingest/IngestSpec.cpp
  src/ingest/SpecRepo.cpp
  src/ingest/test/TestIngestion.cpp
  src/memory/Batch.cpp
  src/memory/Batch.h
  src/memory/encode/DictEncoder.h
  src/memory/serde/TypeData.cpp
  src/memory/serde/TypeData.h
  src/memory/serde/TypeMetadata.h
  src/memory/test/TestEncoder.cpp
  src/meta/Access.h
  src/meta/ClusterInfo.cpp
  src/meta/TableSpec.h
  src/meta/test/TestTableSpec.cpp
  src/service/Service.cmake
  src/service/base/NebulaService.cpp
  src/service/base/NebulaService.h
  src/service/fbs/node.fbs
  src/service/node/NodeClient.cpp
  src/service/node/NodeClient.h
  src/service/node/NodeServer.cpp
  src/service/server/NebulaServer.cpp
  src/service/server/QueryHandler.cpp
  src/service/server/QueryHandler.h
  src/service/test/TestLoadHandler.cpp
  src/service/test/TestQueryHandler.cpp
  src/surface/eval/ValueEval.h
Labels: engine, enhancement, perf

#48 Add Histogram UDAF
  src/api/dsl/Dsl.h
  src/api/dsl/Expressions.h
  src/api/dsl/Serde.cpp
  src/api/test/TestExpressions.cpp
  src/api/test/TestQuery.cpp
  src/api/test/TestUdf.cpp
  src/api/udf/Histogram.h
  src/api/udf/UDFFactory.h
  src/service/server/QueryHandler.cpp
  src/surface/eval/UDF.h
  src/type/Type.h
Labels: engine, enhancement

#59 introduce transform parser [as part of onging evaluation]
  CMakeLists.txt
  ext/PGQuery_Ext.cmake
  src/ingest/Ingest.cmake
  src/ingest/test/TestIngestion.cpp
Labels: exp, question

#64 collect histogram of each column
  ext/Grpc_Ext.cmake
  ext/Openssl_Ext.cmake
  src/api/test/TestQuery.cpp
  src/api/udf/Between.h
  src/api/udf/In.h
  src/execution/BlockManager.cpp
  src/execution/BlockManager.h
  src/execution/TableState.cpp
  src/execution/TableState.h
  src/execution/io/BlockLoader.cpp
  src/memory/Batch.h
  src/memory/DataNode.h
  src/memory/serde/TypeMetadata.h
  src/memory/test/TestHistogram.cpp
  src/meta/NBlock.h
  src/service/fbs/node.fbs
  src/service/http/nebula/dist/node/main.cjs
  src/service/http/nebula/dist/web/main.js
  src/service/http/nebula/dist/web/main2.js
  src/service/http/nebula/index.cjs
  src/service/http/nebula/node.js
  src/service/http/nebula/ui.js
  src/service/node/NodeClient.cpp
  src/service/node/NodeServer.cpp
  src/service/protos/nebula.proto
  src/service/server/NebulaServer.cpp
  src/service/server/NodeSync.cpp
  src/service/server/QueryHandler.cpp
  src/surface/Surface.cmake
  src/surface/eval/Block.h
  src/surface/eval/Histogram.cpp
  src/surface/eval/Histogram.h
  src/surface/eval/ValueEval.cpp
  src/surface/test/TestHistogram.cpp
  src/surface/test/TestSurface.cpp
Labels: api

#72 test latest code and make small updates
  ext/PGQuery_Ext.cmake
  run.sh
  src/api/dsl/Dsl.h
  src/service/http/nebula/index.html
  src/service/http/nebula/web.js
  src/service/http/nebula/web.min.js
  src/service/server/QueryHandler.cpp
Labels: bug
